name: Deploy Client

on:
  push:
    branches: [ master ]

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci, build and test
        run: |
          cd client
          npm ci
          npm run build --if-present
        env:
          REACT_APP_GUN_URL: http://TODOTODOTODOTODOTODOTODOTODO.zolly.ml/gun
      - name: deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./client/build